### ISSUE TITLE
README Change for Non ENV users

### ISSUE THREAD

**Issue by imageaid** [ankane/mapkick#1]
The README currently notes the following: 
Mapkick uses [Mapbox GL JS v1](https://github.com/mapbox/mapbox-gl-js/tree/v1.13.3). To use tiles from Mapbox, [create a Mapbox account](https://account.mapbox.com/auth/signup/) to get an access token and set ENV["MAPBOX_ACCESS_TOKEN"] in your environment.

This is not entirely accurate. When I dug into the code, I found you could also just pass in your `access_token` to the `js_map` method: 
`= js_map([{latitude: 'lotsOnumbers', longitude: 'EvenMOREnumbers'}], access_token: Rails.application.credentials.mapbox[:access_token], style: "mapbox://styles/mapbox/outdoors-v12", zoom: 15, controls: true, width: '100%', height: '600px')`

I would suggest changing the text to something like: 
Mapkick uses [Mapbox GL JS v1](https://github.com/mapbox/mapbox-gl-js/tree/v1.13.3). To use tiles from Mapbox, [create a Mapbox account](https://account.mapbox.com/auth/signup/) to get an access token and set ENV["MAPBOX_ACCESS_TOKEN"] in your environment. If you are using `Rails.application.credentials` instead of `ENV` variables, you can provide your token directly to the `js_map` method by passing in `access_token: my_awesome_token`.

Something like that :) 

Most importantly, thanks for the gem! I needed just something like this for a friend's site and it was so awesomely easy to use and creates a lovely map. Really appreciate all the great work!!

P.S. Apologies for not creating a fork and pul request ... slammed at work this week and wanted to send this thought along before I forgot!

**Comment by ankane** [comment]
Hey @imageaid, thanks for the suggestion. I think most users will want to set it globally, so added a note about `Mapkick.options[:access_token]`.

**Comment by imageaid** [comment]
Heh. Was just about to note you had a much better option and I'll be changing mine shortly! I literally threw it together last weekend and haven't even had a chance to go back and refactor LOL

Thanks, again!
