### ISSUE TITLE
Static Image map support.

### ISSUE THREAD

**Issue by kushagra-03** [ankane/mapkick#10]
Thanks for the great work! 
Is it possible to use the Static Image API to add a map that is just an image, or would that be beyond the scope of this gem? 

Something like:

```erb

<%= img_map [{latitude: 37.7829, longitude: -122.4190}] %>

```

**Comment by ankane** [comment]
Hi @kushagra-03, thanks for the suggestion! Looking at this now. Can you share more about your use case? Also, are you planning to include them on web, emails, or another medium?

**Comment by kushagra-03** [comment]
Thank you @ankane for the prompt response. The use case is quite simple, to just generate an image with a marker. For starters, it would be great to use it on the web. Something like:
<img width="350" alt="Screenshot 2023-04-25 at 9 27 14 PM" src="https://user-images.githubusercontent.com/665657/234334707-1ed10305-4bf3-4617-9a0d-29e158039495.png">
Would be great to leverage the already existing API from mapkick for markers.
Email would be nice to have, although not sure how much extra work that would warrant.

**Comment by ankane** [comment]
Thanks @kushagra-03. Created a [new project](https://github.com/ankane/mapkick-static) for it.
