### ISSUE TITLE
Support for Draggable Markers.

### ISSUE THREAD

**Issue by kushagra-03** [ankane/mapkick#11]
Hello!
Is there a way to make the markers draggable and capture the resulting coordinates?
This example on [Mapbox](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/) captures it quite well.

**Comment by ankane** [comment]
Hi @kushagra-03, you can try using the JavaScript API to add it:

```javascript
const map = Mapkick.maps["map-1"].getMapObject(); // returns mapboxgl.Map
```

but don't think it's common enough to include in the library.

**Comment by ankane** [comment]
Just remembered Mapkick.js uses layers instead of markers (for performance), so don't think it's possible.
