### ISSUE TITLE
There is no ability to pass html data attributes

### ISSUE THREAD

**Issue by loqimean** [ankane/mapkick#13]
There is a problem when I wanna connect to my map Stimulus.js controller and I can't! 'cause there is no such ability!

**Comment by ankane** [comment]
Hi @loqimean, you can put the map in a `div` with any attributes.

**Comment by loqimean** [comment]
but it's a workaround.., it's like `simple_form`, rails with `link_to`, `image_tag` etc. said you wrap your link or image, to have the ability set something to your element, the again workaround in CSS, JS, where you should use selectors, like `.map > div` or `.map > svg`, in JS also NOT `this.element`, but using getters and another stuff, like `this.element.quarySelector("svg")` . I don't think that it's good

**Comment by loqimean** [comment]
Btw, what If I create a pull request to add this feature?
