### ISSUE TITLE
LINESTRING

### ISSUE THREAD

**Issue by doctorjane** [ankane/mapkick#16]
area_map was a great addition of mapkick! It would be very useful to have a geojson LINESTRING so that one can show a path through an area_map.

 {:type=>"LineString", :coordinates=>[[-122.42562, 37.61791], [-122.4261, 37.61818], [-122.42638, 37.61825], [-122.42657, 37.61825], [-122.42776, 37.6181]]}

thank you for creating ChartKick and now MapKick!

**Comment by ankane** [comment]
Hi @doctorjane, thanks for the suggestion. Can you share more about the high level use case?
