### ISSUE TITLE
Can I use Mapkick to plot directions?

### ISSUE THREAD

**Issue by pedrogusfer** [ankane/mapkick#2]
Hey, there!

I want to plot some directions using Mapbox's Directions API.

Is Mapkick only to plot specific dots or do you think I can use it to plot routes?

**Comment by ankane** [comment]
Hey @pedroaugustofsilva, thanks for the suggestion. Don't think it's something I want to add/support right now, but may revisit in the future. If someone decides to fork Mapkick.js and add it, I'd be curious to see it.
