### ISSUE TITLE
A help to add circle radius to mapkick and static mapkick

### ISSUE THREAD

**Issue by dcalixto** [ankane/mapkick#20]
Hello i trying to add this like in the print 
![map-circle](https://github.com/ankane/mapkick/assets/1009077/482f92ba-ae2c-4c44-a829-7a38b29e8183)

with this helper

```
  def createGeoJSONCircle(coordinates, radius = 2, points = 64)
    coordinate = {
      longitude: coordinates.first[0].to_f,
      latitude: coordinates.first[1].to_f
    }

    ret = []
    # radius is set in kilometers
    distanceX = radius / (111.320 * Math.cos(coordinate[:latitude] * Math::PI / 180))
    distanceY = radius / 110.574

    for i in 0..points
      theta = (i.to_f / points.to_f) * (2 * Math::PI)
      x = distanceX * Math.cos(theta)
      y = distanceY * Math.sin(theta)

      ret << [(coordinate[:longitude] + x).to_s, (coordinate[:latitude] + y).to_s]
    end
    ret << ret.first
    ret
  end
```

but the code for static return:
  <%= static_map  createGeoJSONCircle([@post.location.latitude, @post.location.longitude]) %>

`undefined method `[]' for an instance of Float`

and `missing latitude (index: 0)` 
for   <%= js_map createGeoJSONCircle([latitude: @post.location.latitude, longitude: @post.location.longitude]) %>

So this can be accomplished with ruby?

**Comment by ankane** [comment]
Hi @dcalixto, you can use an area map for this, which supports any GeoJSON `Polygon` or `MultiPolygon` (within the max request size for static maps).

```erb
<%= area_map [{geometry: {type: "Polygon", coordinates: ...}}] %>
```
