### ISSUE TITLE
Remove escaping from tooltip in js_map rendering.

### ISSUE THREAD

**Issue by tiagocassio** [ankane/mapkick#24]
Hi,

First of all i want to thank you for creating this awesome gem.

Second, i'm stucked on a little thing. Here is my situation:

I have a js map called like:

`<%= js_map api_v1_domiciles_url(format: :json), controls: true, refresh: 300, height: '900px', width: '100%', tooltip: { hover: true, html: true } %>`

And here is my json view:

![image](https://github.com/user-attachments/assets/6f89850d-1ae1-4468-a39d-1217947eb19c)

When the map is rendered, the tooltip is escaping the html, and not possibiliting to render the link correctly:

![image](https://github.com/user-attachments/assets/0dfde61a-18a3-45c7-8f51-cb437d749d8d)

Where i'm missing?

**Comment by ankane** [comment]
Hi @tiagocassio, try `tooltips:` instead of `tooltip:` (in the `js_map` call).
