### ISSUE TITLE
Ability to draw and highlight polygons

### ISSUE THREAD

**Issue by DemiGodAugus** [ankane/mapkick#5]
Great gem that's made getting a map and setting it up pretty easy. However, I was wondering if it is possible to draw a polygon outlined with coordinates and fill it with a color?

**Comment by ankane** [comment]
Hey @DemiGodAugus, it's not currently possible, but may add more map types in the future. I'd be curious to hear use cases / more details if anyone interested in this wants to share.

I imagine the data format could look like:

```erb
<%= polygon_map [{coordinates: [...], tooltip: "", label: ""}] %>
```

or maybe support passing GeoJSON directly.

**Comment by DemiGodAugus** [comment]
@ankane Hey, thanks for the reply. In terms of use case, in my case, it's more for highlighting specific regions. In the app that I'm currently working on, we receive reports from within specific jurisdictions (each with GeoJSON data highlighting their boundaries) and would like to have them highlighted just as a visual indicator as to where they belong to.

**Comment by ankane** [comment]
Added experimental support for area maps in the commit above (supports both `Polygon` and `MultiPolygon` types)

```ruby
<%= area_map [{geometry: {type: "Polygon", coordinates: [...]}, label: "Hello", tooltip: "World"}] %>
```

<strike>Note that labels and tooltips aren't supported yet</strike>

**Comment by ankane** [comment]
Just pushed 0.1.2 (with a few improvements). Feel free to create a new issue if there's any feedback on this.

**Comment by ghost** [comment]
Hey @ankane.
Is highliting working? It's showing me an array of those coordinates but no highliting :C

My params
[[74.2503655987721, 40.5091442241349], [74.2504120352793, 40.5091183000754], [74.2503322759711, 40.5090405104492], [74.2503655987721, 40.5091442241349]]
