### ISSUE TITLE
Custom pin icons?

### ISSUE THREAD

**Issue by whatnotery** [ankane/mapkick#8]
I'm not sure how difficult this would be to implement as I haven't dug into the codebase yet but being able to pass a link to an image as an argument for custom pin icons would be really neat!

**Comment by whatnotery** [comment]
Ahh just saw [this issue](https://github.com/ankane/mapkick.js/issues/1) on Mapkick.js which I'm assuming is needed to resolve this one

**Comment by ankane** [comment]
Hey @whatnotery, yeah, it would need to be added there. However, it'll add some complexity, so I'm not sure it's something I'd like to add right now.
