### ISSUE TITLE
Question: Which format is used for the area_map?

### ISSUE THREAD

**Issue by Bergrebell** [ankane/mapkick#9]
In the README and examples it only says: 

`<%= area_map [{geometry: {type: "Polygon", coordinates: ...}}] %>`

So what format is expected here? I have tried it in the format used by Mapbox GL without success.

**Comment by ankane** [comment]
Hi @Bergrebell, the format is a GeoJSON `Polygon` or `MultiPolygon`.

https://github.com/ankane/mapkick#area-map

**Comment by Bergrebell** [comment]
Hi @ankane - thanks for the swift response. i'm really sorry but i still cannot get it to work. 

```
<%= area_map [
               {
                 geometry: {
                   type: "Polygon", coordinates: [[-67.13734, 45.13745], [-66.96466, 44.8097], [-68.03252, 44.3252], [-69.06, 43.98], [-70.11617, 43.68405], [-70.64573, 43.09008], [-70.75102, 43.08003], [-70.79761, 43.21973], [-70.98176, 43.36789], [-70.94416, 43.46633], [-71.08482, 45.30524], [-70.66002, 45.46022], [-70.30495, 45.91479], [-70.00014, 46.69317], [-69.23708, 47.44777], [-68.90478, 47.18479], [-68.2343, 47.35462], [-67.79035, 47.06624], [-67.79141, 45.70258], [-67.13734, 45.13745]]
                 }
               }
             ] %>
```

this is what i have tried, which actually gives me a zoomed-out map without any polygon inside (as far as i can see). from what i have seen on google and in the Mapbox GL documentation this should be the right format. what am i missing?

**Comment by Bergrebell** [comment]
never mind. the GeoJSON polygon needs three square brackets instead of [two.](https://www.ibm.com/docs/en/db2/11.5?topic=formats-geojson-format) this works:

```
<%= area_map [
               {
                 geometry: {
                   type: "Polygon", coordinates: [[[-67.13734, 45.13745], [-66.96466, 44.8097], [-68.03252, 44.3252], [-69.06, 43.98], [-70.11617, 43.68405], [-70.64573, 43.09008], [-70.75102, 43.08003], [-70.79761, 43.21973], [-70.98176, 43.36789], [-70.94416, 43.46633], [-71.08482, 45.30524], [-70.66002, 45.46022], [-70.30495, 45.91479], [-70.00014, 46.69317], [-69.23708, 47.44777], [-68.90478, 47.18479], [-68.2343, 47.35462], [-67.79035, 47.06624], [-67.79141, 45.70258], [-67.13734, 45.13745]]]
                 }
               }
             ] %>
```
